---
abstract: 'implementation of AGA BayRate (player ratings) as perl object'
author:
  - 'Reid Augustin <reid@hellosix.com>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Go-AGA-BayRate
requires:
  Carp: 0
  DBI: 0
  Date::Parse: 0
  DateTime: 0
  Getopt::Long: 0
  IO::File: 0
  Inline: 0
  Math::GSL::BLAS: 0
  Math::GSL::Const: 0
  Math::GSL::Errno: 0
  Math::GSL::Interp: 0
  Math::GSL::Linalg: 0
  Math::GSL::Matrix: 0
  Math::GSL::Multimin: 0
  Math::GSL::Permutation: 0
  Math::GSL::SF: 0
  Math::GSL::Spline: 0
  Math::GSL::Vector: 0
  Readonly: 0
  Scalar::Util: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
version: 0.063
